apiVersion: v1
kind: Service
metadata:
  name: bulk-service
  labels:
    app: bulk-service
spec:
  selector:
    app: bulk-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

